### ISSUE TITLE
Darwin: DiskIO uses CGO

### ISSUE THREAD

**Issue by jabdr** [it-novum/openitcockpit-agent-go#23]

**Comment by ibering** [comment]
Auf dem Catalina System (Version 10.15.7) tritt beim Ausführen des DiskIO Checks folgender Fehler auf:

`level=error msg="Push client:  could not unmarshal server response: invalid character '<' looking for beginning of value"`

**Comment by nook24** [comment]
After searching the web for many hours there is no alternative than using CGO.
It looks like the only tool build into macOS is `fs_usage -f diskio -t 1 ` But this displays I/O per process. (I also guess this is used by Activity Monitor in the background).

Tools like `iosnoop` or `iotop` depanding on `dtrace` which is disabled on modern macOS systems.

We will continue using [gopsutil](https://github.com/shirou/gopsutil/blob/v3.21.4/v3/disk/iostat_darwin.c#L1) which is based on https://github.com/lufia/iostat. This is also used by the Prometheus node_exporter: https://github.com/prometheus/node_exporter/blob/v1.1.2/collector/diskstats_darwin.go#L22
