### ISSUE TITLE
Create Check for Windows Event Log

### ISSUE THREAD

**Issue by nook24** [it-novum/openitcockpit-agent-go#46]
At the moment the openITCOCKPIT Monitoring Agent is collecting Windows Event Log data but there is not check plugin available to monitor those records.

EntryTypes: https://docs.microsoft.com/de-de/dotnet/api/system.diagnostics.eventlogentrytype?view=net-5.0

**Comment by nook24** [comment]
Idee für einen Check: (Brainstorming mit @Terminator81)

Für jedes übermittelte Logfile (System, Applications, ...) kann man einen Check erstellen. Dort kann man dann auf den EntryType/s (Fehler, Information) filtern, auf EventID/s und einen String (enthält "firefox") filtern

Der Check könnte dann sowas ausgeben wie:
`Ok: No Records found`
oder `Error 15 records found`
Im Long Output könnte man sich noch überlegen die einzelnen Meldungen anzuzeigen

Das Erstellen der Checks soll über das Discovery erfolgen. Bei dem Eventlog-Check ist das natürlich so eine Sache da man dort in der Regel ja auf etwas Filtern möchte. Ich würde es deshalb so einbauen, das man im Discovery nur die Eventlogs auswählen kann, und dann werden dort erst einmal alle Events außer `Information und SuccessAudit` als schlecht behandelt. Und in den Einstellungen von dem Check kann man dann nochmal genauere Filter hinterlegen.

**Comment by Terminator81** [comment]
Klingt gut 🤪🤪🤪🤪

**Comment by nook24** [comment]
Plugin wurde hinzugefügt und wird mit der Stable Version zur Verfügung stehen.
![Bildschirmfoto 2021-04-30 um 16 10 31](https://user-images.githubusercontent.com/9019992/116710390-ff373800-a9d1-11eb-9621-40e442d63005.png)

![Bildschirmfoto 2021-04-30 um 16 09 47](https://user-images.githubusercontent.com/9019992/116710401-02cabf00-a9d2-11eb-8d8f-2d0426306078.png)
