### ISSUE TITLE
Missing inbound firewall rule on Windows Server 2008 R2

### ISSUE THREAD

**Issue by Cynexxde** [it-novum/openitcockpit-agent-go#63]
**Agent Mode**:
* Pull Model

**Versions**
* openITCOKPIT Server Version: 4.3.0
* openITCOCKPIT Monitoring Agent Version: 3.0.7

**Operating system**
Windows Server 2008 R2

* No Proxy
* I am using AutoTLS
* Used CPU architecture: amd64

**Describe the bug**
When installing the agent, no inbound firewall rule is created on Windows Server 2008 R2. I have now created these manually for each system. Everything works now. I just wanted to let you know.

**Comment by nook24** [comment]
@wx-db Install the agent using the msi. Ignore the error in the log and just create the firewall rule manually using the Windows GUI. That's should be it.

**Comment by Cynexxde** [comment]
![image](https://user-images.githubusercontent.com/88704661/150500073-53ec3457-409e-4f05-bdd8-9229d17b61fd.png)
