### ISSUE TITLE
Feature: Systemlaufzeit

### ISSUE THREAD

**Issue by Cynexxde** [it-novum/openitcockpit-agent-go#64]
Hallo zusammen,
ich würde mich über eine Anzeige des letzten Systemstarts und der Uptime freuen. Der Check kann dann ja check_oitc_agent_uptime oder so heißen. 

Zusätzlich würde ich die Systemlaufzeit in Minuten als Performancedaten hinzufügen, denn dann kann über den Graphen nachvollzogen werden wann und wie oft das System über ein bestimmten Zeitraum neu gestartet wurde.

Ich stelle mir den Output in etwa so vor:
OK:  Systemstart: 09.09.2021 02:05:37, System runtime: 94 days 18 hours 28 minutes | uptime=28minutes;

**Comment by Cynexxde** [comment]
Hey zusammen, ich wollte einfach mal nachhacken, da ja schon etwas Zeit seit meiner Anfrage vergangen ist. Besteht die Option, dass es in ähnlicher Form implementiert wird?

**Comment by Cynexxde** [comment]
@nook24 könnte ich ein kurzes Feedback bekommen?

**Comment by Cynexxde** [comment]
Im Agent Output ist die Uptime auch bereits enthalten. Somit sollte es doch mit überschaubarem Aufwand möglich sein oder?

![image](https://github.com/it-novum/openitcockpit-agent-go/assets/88704661/f5bda1a3-4c4e-4dfa-8efd-2ccc08b60ed5)

**Comment by nook24** [comment]
Hi @Cynexxde Korrekt, der Wert für Uptime wird bereits vom Agenten ausgelesen und übermittelt. Die Werte müssen allerdings noch einer Plausibilitätsprüfung unterzogen werden.

Der Check-Receiver kann die Uptime aktuell nicht verarbeiten, dort fehlt noch ein Check und das zugehörige Servicetemplate. Der Aufwand dafür hält sich in Grenzen.

Ich versuche es mal zwischen den Jahren unter zu bringen.

**Comment by Cynexxde** [comment]
Das hört sich gut an. Vielen Dank schonmal ^^

**Comment by nook24** [comment]
Feature wurde umgesetzt 🥳

https://github.com/it-novum/openITCOCKPIT/pull/1613
