### ISSUE TITLE
different status feedback

### ISSUE THREAD

**Issue by carman2022** [it-novum/openitcockpit-agent-go#74]
**Agent Mode**:
* [x] Pull Model (openITCOCKPIT Server request data from Agent)
* [ ] Push Model (Agent send data to openITCOCKPIT)

**Versions**
* openITCOCKPIT Monitoring Agent Version: 3.x.x

**Operating system**
Debian GNU/Linux 11 (bullseye)

* Do you use an HTTP proxy? -> no
* Are you using Auto-TLS, HTTPS or HTTP? -> yes
* Used CPU architecture: i386, amd64, arm64 or armhf? -> amd64

**Describe the bug**
Substate other than running is issued as a warning. i have installed ufw firewall and postfix, 
Substate is: (code=exited, status=0/SUCCESS)

![image](https://user-images.githubusercontent.com/116793831/198243362-4c4982a8-74d0-4a23-b70e-f1156c909037.png)

![image](https://user-images.githubusercontent.com/116793831/198243682-e689ac0d-5b6e-414e-8124-35d5c839bac4.png)

**Comment by nook24** [comment]
More information about what should be considered as successful by the Agent can be found here:
https://www.computernetworkingnotes.com/linux-tutorials/systemd-units-explained-with-types-and-states.html

At the moment only `Active (running)` is considered successfully. `Active (exited)` and `Active (waiting)` should also be added to the consideration list

**Comment by nook24** [comment]
Tracked by ITC-2885

**Comment by ibering** [comment]
This issue will be resolved in an upcoming version of openITCOCKPIT
