### ISSUE TITLE
large cpu utilization during the day from summer to winter time

### ISSUE THREAD

**Issue by Electricz1337** [it-novum/openitcockpit-agent-go#82]
**Agent Mode**:
 [x] Pull Model (openITCOCKPIT Server request data from Agent)

**Versions**
openITCOKPIT Server Version: 4.6.8
openITCOCKPIT Monitoring Agent Version: 3.0.9

**Operating system**
Ubuntu 22.04, Windows Server 2016, 2019 & 2022

* Do you use an HTTP proxy?
* Are you using Auto-TLS, HTTPS or HTTP?
Auto-TLS

**Describe the bug**
CPU Load seems to load up by end of the day when the summer time changed to winter time.

**To Reproduce**
Check CPU Load on 30.10.2023 from 23:00 - 24:00

**Expected behavior**
No change in CPU Load

**Screenshots**
![image](https://github.com/it-novum/openitcockpit-agent-go/assets/30772723/16ddf1a5-4450-42c2-be49-17a7e9e22c86)
![image](https://github.com/it-novum/openitcockpit-agent-go/assets/30772723/32345be5-6fbb-4be6-832f-0942990792b4)

also from last year:
![image](https://github.com/it-novum/openitcockpit-agent-go/assets/30772723/f4806698-5fb9-457f-8422-c7a80b57e422)

**Additional context**
Proven by wheeleRR on Discord who recreated the issue

**Comment by nook24** [comment]
I can confirm that this issue occurred on all systems (Windows, macOS and Linux). 

Windows:
![grafik](https://github.com/it-novum/openitcockpit-agent-go/assets/9019992/c4c5a9bb-4dbf-489e-afa7-a2e672b7f9fe)

Linux:
![grafik](https://github.com/it-novum/openitcockpit-agent-go/assets/9019992/addaf203-9437-4c9f-8b78-ef5d681fbc3d)

Some more context in Germen:
Die Zeitumstellung von Sommer auf Winterzeit war am 29. Oktober 2023. Das Problem trat dann am 30. Oktober von 23:00 bis 24:00 Uhr auf und ist danach wieder verschwunden.

**Comment by nook24** [comment]
Maybe this has something to do with the log rotate?

https://github.com/it-novum/openitcockpit-agent-go/blob/46030aa05fb3ea73c22c31fda12465dab7608994/loghandler/loghandler.go#L98-L101

![agent_logrotate](https://github.com/it-novum/openitcockpit-agent-go/assets/9019992/0ddaed1d-fad4-46e8-96db-d264b0aae2b9)

**Comment by ibering** [comment]
Tracked by OA-49

**Comment by ibering** [comment]
Unfortunately, local time zone was taken into account instead of using UTC

15 October

![15 10](https://github.com/it-novum/openitcockpit-agent-go/assets/9592910/1cf80da3-24c9-495b-a00a-7a96a3e75adb)

29 October

![29 10](https://github.com/it-novum/openitcockpit-agent-go/assets/9592910/3d506626-0060-4845-89d6-634f14a318ea)

**Comment by nook24** [comment]
This issue is now resolved and will be part of version 3.0.12 :)
https://github.com/it-novum/openitcockpit-agent-go/pull/83
